import unittest
import io
from extraction_helpers import load_functions

try:
    from reportlab.graphics.barcode import qr as _qr_encoder
    from PIL import Image
    import cv2
    import numpy as np
    DEPS_AVAILABLE = True
except ImportError:
    DEPS_AVAILABLE = False


@unittest.skipUnless(DEPS_AVAILABLE, "reportlab/PIL/cv2 not installed in this environment")
class TestAssetQR(unittest.TestCase):
    """QR generation and scanning were built together and verified
    together during development; this keeps that same round-trip
    check runnable going forward instead of only having existed as a
    one-time manual verification."""

    @classmethod
    def setUpClass(cls):
        cls.ns = load_functions(
            "generate_asset_qr", "decode_asset_qr",
            extra_globals={
                "QR_GENERATION_AVAILABLE": True,
                "QR_SCANNING_AVAILABLE": True,
                "_qr_encoder": _qr_encoder,
                "Image": Image,
                "cv2": cv2,
                "np": np,
            },
        )
        cls.generate_asset_qr = staticmethod(cls.ns["generate_asset_qr"])
        cls.decode_asset_qr = staticmethod(cls.ns["decode_asset_qr"])

    def _image_to_bytes(self, img):
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()

    def test_round_trip_encodes_and_decodes_correctly(self):
        img = self.generate_asset_qr(42)
        decoded = self.decode_asset_qr(self._image_to_bytes(img))
        self.assertEqual(decoded, 42)

    def test_different_asset_ids_produce_different_decodable_codes(self):
        for asset_id in [1, 100, 9999]:
            with self.subTest(asset_id=asset_id):
                img = self.generate_asset_qr(asset_id)
                decoded = self.decode_asset_qr(self._image_to_bytes(img))
                self.assertEqual(decoded, asset_id)

    def test_unrelated_qr_code_is_rejected_not_falsely_matched(self):
        """A photo of some OTHER QR code (a URL, a WiFi QR, anything
        not generated by this app) must never be treated as a valid
        asset scan."""
        other = _qr_encoder.QrCodeWidget("https://example.com")
        other.qr.make()
        inner = other.qr
        mc = inner.getModuleCount()
        from PIL import ImageDraw
        img = Image.new("RGB", ((mc + 8) * 10, (mc + 8) * 10), "white")
        d = ImageDraw.Draw(img)
        for row in range(mc):
            for col in range(mc):
                if inner.isDark(row, col):
                    d.rectangle([(col+4)*10, (row+4)*10, (col+5)*10, (row+5)*10], fill="black")
        decoded = self.decode_asset_qr(self._image_to_bytes(img))
        self.assertIsNone(decoded)

    def test_invalid_bytes_fail_safely_rather_than_raise(self):
        decoded = self.decode_asset_qr(b"not an image at all")
        self.assertIsNone(decoded)


if __name__ == "__main__":
    unittest.main()
